dist: xenial

before_install:
  - sudo apt-get update -qq
  # These are gem5 dependencies.
  - sudo apt-get install -y m4
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y libprotobuf-dev
  - sudo apt-get install -y protobuf-compiler
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y scons
  - sudo apt-get install -y libpython2.7 libpython2.7-dev
  # These are Aladdin dependencies.
  - sudo apt-get install -y libboost-graph-dev
  - sudo apt-get install -y libpthread-stubs0-dev
  # Install pre-built LLVM 6.0. This doesn't actually work for tracing, but it
  # at least lets gem5-Aladdin to build by letting it set LLVM_VERSION
  # correctly.
  - |
    pushd /tmp
    wget -q http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    tar -xf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    cd clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04
    sudo cp -rf bin/ /usr/local/
    sudo cp -rf include/ /usr/local/
    sudo cp -rf lib /usr/local/
    sudo cp -rf libexec /usr/local/
    sudo cp -rf share /usr/local/
    popd
  - git submodule update --init --recursive

env:
  - ALADDIN_HOME=$PWD/src/aladdin BOOST_ROOT=/usr/include/boost PATH=/usr/local/bin:$PATH

language: c++
compiler:
  - g++

script:
  - python run_travis.py

cache:
  timeout: 1000
  directories:
      # This DB stores all the file signatures, which SCons uses to determine
      # what has changed.
    - build/sconsign
      # This stores the conftest files used to check for dependencies.
      # Unfortunately, these C files also get recorded in the sconsign DB, so
      # if the DB thinks they're present but we don't cache them, checking for
      # dependencies will fail.
    - build/.scons_config
      # Cache everything we're not likely to modify. So exclude aladdin and all
      # top level files in mem, sim, and dev.
    - build/X86/arch
    - build/X86/cpu
    - build/X86/proto
    - build/X86/python
    - build/X86/enums
    - build/X86/base
    - build/X86/gpu-compute
    - build/X86/unittest
    - build/X86/debug
    - build/X86/params
    - build/X86/kern
    - build/X86/mem/protocol
    - build/X86/mem/cache
    - build/X86/mem/ruby
    - build/X86/mem/probes
    - build/X86/sim/power
    - build/X86/sim/probe
    - build/X86/dev/alpha
    - build/X86/dev/arm
    - build/X86/dev/i2c
    - build/X86/dev/mips
    - build/X86/dev/net
    - build/X86/dev/pci
    - build/X86/dev/sparc
    - build/X86/dev/storage
    - build/X86/dev/virtio
    - build/X86/dev/x86

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - slxi1202@gmail.com
      - yaoyuannnn@gmail.com
